[build]
  command = "npm run build"
  publish = "build"
  functions = ".netlify/functions/"

[dev]
  command = "npm start"
  publish = "public"
  functions = "functions/"
  Port= 8888
  functionsPort= 3333

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "functions/*"
  to = "functions/:splat"
  status = 200
