[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions/"

[dev]
  command = "npm start"
  publish = "public"
  functions = "netlify/functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "netlify/functions/*"
  to = "netlify/functions/:splat"
  status = 200